openapi: 3.0.0
info:
  title: Conceal Core API Documentation
  version: "6.7.2"
  description: API documentation for Conceal Core
  contact:
    name: Conceal Help Desk
    url: https://conceal.network/support

servers:
  - url: "http://localhost:16000"
    description: Mainnet local node
  - url: "http://localhost:16600"
    description: Testnet local node

tags:
  - name: JSON-RPC

paths:
  /json_rpc:
    post:
      summary: Get Blocks List
      description: Retrieve the list of the 30 blocks preceding a given block height, and the block at the given height using JSON-RPC.
      operationId: getBlocksList
      tags: ["JSON-RPC"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetBlocksListRequest"
      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBlocksListResponse"

components:
  schemas:
    GetBlocksListRequest:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        method:
          type: string
          enum: ["f_blocks_list_json"]
        params:
          $ref: "#/components/schemas/getBlocksListParams"
        id:
          type: string
          example: "1"
      required:
        - jsonrpc
        - method
        - params
        - id

    getBlocksListParams:
      type: object
      properties:
        height:
          type: integer
          description: The height of the block.
          example: 12345

    GetBlocksListResponse:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        result:
          $ref: "#/components/schemas/GetBlocksListResult"
        id:
          type: string
          example: "1"

    GetBlocksListResult:
      type: object
      properties:
        blocks:
          type: array
          items:
            $ref: "#/components/schemas/BlockShort"
          example:
            - timestamp: 1633510598
              height: 12345
              difficulty: 74
              hash: 20e93738606e150ea3f2dd30b4b60fd9af2db05b6aecdd1201159a4e50455d44
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633510318
              height: 12344
              difficulty: 78
              hash: 09371a62201ba2393b2e250bc101e9e772e8bbab3b02ebddcdd3e35e5dd17c4c
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633510013
              height: 12343
              difficulty: 77
              hash: d61e4bab173f2d737156e4cb9b11755f71f300de9fa6076e134f43f15d14f6e0
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509936
              height: 12342
              difficulty: 77
              hash: 66b916b3013b373b605f6b98539d15b962af2561d383ba2a48299b4151ec3e5b
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509810
              height: 12341
              difficulty: 79
              hash: c2e3cc90f927898c49120513c3ca8f6423e526abae8f1aacfe5295a25d6a411d
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509619
              height: 12340
              difficulty: 77
              hash: a2dd421ffb515ffcf647a0a875b2c82a3e5a47e6e40ac8de9fb58a6bcf18b38d
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509605
              height: 12339
              difficulty: 78
              hash: d50ede088718dcb5c233fee4d21d01a6e673947fa794daf634e02f3c617981a7
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509405
              height: 12338
              difficulty: 77
              hash: d17fb668c9e9434cd207b44af4b7de6840f5c356f36b6a3d61b22535bf0aaac3
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509347
              height: 12337
              difficulty: 77
              hash: d42b8a4529297e7932a6b9bac70eb84c350955c77028d92280c5eca64cbfbdf5
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509228
              height: 12336
              difficulty: 78
              hash: e75cc640981a1d1099f721f81962a78eda964708e3c240207140ad6f94f61935
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633509081
              height: 12335
              difficulty: 79
              hash: ed90940618bfdc63dd769260bed5c58bc5d04e5776b131c7c0c5442576fe3ad3
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508878
              height: 12334
              difficulty: 79
              hash: e6c668531bdd470435f1b697867b8a03b215f85b708495917b5be93365afbd07
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508815
              height: 12333
              difficulty: 76
              hash: dc38fd26025d9c4c54c37728be9766e11ebabaef99394bf01b80230b04f94775
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508808
              height: 12332
              difficulty: 77
              hash: 3da2b11ee70eaaa99034f0dcebca8769d4d693e7f4022a2fbbf58f3ec25e6ff7
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508703
              height: 12331
              difficulty: 79
              hash: 4331bdc9c4b8aa2228607c484d604fca8ca35bc5b671d0c7bda41876a9e9bf0d
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508416
              height: 12330
              difficulty: 84
              hash: c28b448a3de849e16c3e45a145a5f56db4c26966b117e95dd4807b00ff83033d
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633508071
              height: 12329
              difficulty: 83
              hash: a91b363ef1d16648599732f5012ad30a7231be5a4332aeba38295516a9dfb608
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507957
              height: 12328
              difficulty: 86
              hash: 4fdc4c7f29f212fbfff15cc8f054e5b48a0f2e74217cca1eb81de0e6cde45679
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507761
              height: 12327
              difficulty: 86
              hash: d695c0c6b692c223f83af58f8ad0966a10467c982e4cd5acd46f43df8f8f14b6
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507619
              height: 12326
              difficulty: 85
              hash: 9f1e241340ca746089032437e59899c215aabc0e2c36d0326a991d7e555567a2
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507556
              height: 12325
              difficulty: 85
              hash: 2b0df5c7e0f321357aa1c86dea7f36359d4d4da611fa387cfe4d748697f465d1
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507407
              height: 12324
              difficulty: 84
              hash: 9f1fba9cab2d67c03d18e9f184e4dd598b2b2bcc384d25836fb0b5e57ad387b2
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507358
              height: 12323
              difficulty: 86
              hash: 623ae4899650e00733ba8a175843ab1af48f366d0776d7f501d674d76f6c8418
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507186
              height: 12322
              difficulty: 86
              hash: b7079f58b17cc2680744b54051b28894c23fb981bbc563fe52d263dfc916863e
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633507039
              height: 12321
              difficulty: 86
              hash: 92de5201d785528d230a0903c9e3cd8d3be090c99091802879a81f094cbd37cd
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506906
              height: 12320
              difficulty: 85
              hash: 86b2c086c048fefe7a0a2af887e1270834f9466371040a6b568c5b4da9fbe03f
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506878
              height: 12319
              difficulty: 89
              hash: 609a7a544146d7045dde332aa319d46e330c4af26e4056065732ad29fafa2ed7
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506550
              height: 12318
              difficulty: 88
              hash: 334e2a2517cb0940fecc2d404e4b5c0caae26c54790051dd1cb13dfac7b1c6e8
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506499
              height: 12317
              difficulty: 86
              hash: b94010e3064c25a20468af4bffb76771b2e69e69159a6e805fd165ea53445308
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506457
              height: 12316
              difficulty: 84
              hash: 4dab830162ff197b06d1750c2364e068eecdca275b37b8ba3cdb58b9200466b6
              tx_count: 1
              cumul_size: 123
            - timestamp: 1633506450
              height: 12315
              difficulty: 86
              hash: 8c4707306735750c41d66a2714a4027b9744fbf0a8658deb46800302f0d03c33
              tx_count: 1
              cumul_size: 123

        status:
          type: string
          description: The status of the operation
          example: OK

    BlockShort:
      type: object
      properties:
        timestamp:
          type: integer
          description: The timestamp of the block.
          example: 1633510598
        height:
          type: integer
          description: The height of the block.
          example: 12345
        difficulty:
          type: integer
          description: The difficulty of the block.
          example: 74
        hash:
          type: string
          description: The hash of the block.
          example: 20e93738606e150ea3f2dd30b4b60fd9af2db05b6aecdd1201159a4e50455d44
        tx_count:
          type: integer
          description: The number of transactions in the block.
          example: 1
        cumul_size:
          type: integer
          description: The cumulative size of the block.
          example: 123
