openapi: 3.0.0
info:
  title: Conceal Core API Documentation
  version: "6.7.2"
  description: API documentation for Conceal Core
  contact:
    name: Conceal Help Desk
    url: https://conceal.network/support

servers:
  - url: "http://localhost:16000"
    description: Mainnet local node
  - url: "http://localhost:16600"
    description: Testnet local node

tags:
  - name: JSON-RPC

paths:
  /json_rpc:
    post:
      summary: Get Transactions from the Pool
      description: Retrieve transactions from the transaction pool using JSON-RPC.
      operationId: getTransactionsFromPool
      tags: ["JSON-RPC"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetTransactionsFromPoolRequest"
      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTransactionsFromPoolResponse"

components:
  schemas:
    GetTransactionsFromPoolRequest:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        method:
          type: string
          enum: ["f_on_transactions_pool_json"]
        params:
          $ref: "#/components/schemas/EmptyParams"
        id:
          type: string
          example: "1"
      required:
        - jsonrpc
        - method
        - params
        - id

    EmptyParams:
      type: object
      additionalProperties: false

    GetTransactionsFromPoolResponse:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        result:
          $ref: "#/components/schemas/GetTransactionsFromPoolResult"
        id:
          type: string
          example: "1"

    GetTransactionsFromPoolResult:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/TransactionShort"
        status:
          type: string
          example: OK

    TransactionShort:
      type: object
      properties:
        hash:
          type: string
          description: The hash of the transaction.
          example: 030e1d9fb2a672c8ac99d0d684f7189221e2ae1143fe69e1524fdd3b0db8cbff
        fee:
          type: integer
          description: The fee for the transaction.
          example: 1000
        amount_out:
          type: integer
          description: The amount out for the transaction.
          example: 6000000
        size:
          type: integer
          description: The size of the transaction.
          example: 2170
