openapi: 3.0.0
info:
  title: Conceal Core API Documentation
  version: "6.7.2"
  description: API documentation for Conceal Core
  contact:
    name: Conceal Help Desk
    url: https://conceal.network/support

servers:
  - url: "http://localhost:16000"
    description: Mainnet local node
  - url: "http://localhost:16600"
    description: Testnet local node

tags:
  - name: JSON-RPC

paths:
  /json_rpc:
    post:
      summary: Get Block Header by Hash
      description: Retrieve the block header by hash using JSON-RPC.
      operationId: getBlockHeaderByHash
      tags: ["JSON-RPC"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetBlockHeaderByHashRequest"
      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBlockHeaderByHashResponse"

components:
  schemas:
    GetBlockHeaderByHashRequest:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        method:
          type: string
          enum: ["getblockheaderbyhash"]
        params:
          $ref: "#/components/schemas/GetBlockHeaderByHashParams"
        id:
          type: string
          example: "1"
      required:
        - jsonrpc
        - method
        - params
        - id

    GetBlockHeaderByHashParams:
      type: object
      properties:
        hash:
          type: string
          description: The hash of the block.
          example: 20e93738606e150ea3f2dd30b4b60fd9af2db05b6aecdd1201159a4e50455d44

    GetBlockHeaderByHashResponse:
      type: object
      properties:
        jsonrpc:
          type: string
          enum: ["2.0"]
        result:
          $ref: "#/components/schemas/GetBlockHeaderByHashResult"
        id:
          type: string
          example: "1"

    GetBlockHeaderByHashResult:
      type: object
      properties:
        block_header:
          $ref: "#/components/schemas/BlockHeader"
        status:
          type: string
          description: The status of the operation
          example: OK

    BlockHeader:
      type: object
      properties:
        major_version:
          type: integer
          description: The major version of the block.
          example: 8
        minor_version:
          type: integer
          description: The minor version of the block.
          example: 0
        timestamp:
          type: integer
          description: The timestamp of the block.
          example: 1633510598
        prev_hash:
          type: string
          description: The hash of the previous block.
          example: 09371a62201ba2393b2e250bc101e9e772e8bbab3b02ebddcdd3e35e5dd17c4c
        nonce:
          type: integer
          description: The nonce of the block.
          example: 3425989702
        orphan_status:
          type: boolean
          description: Whether the block is an orphan.
          example: false
        height:
          type: integer
          description: The height of the block.
          example: 12345
        depth:
          type: integer
          description: The depth of the block.
          example: 123456
        deposits:
          type: integer
          description: The deposits of the block.
          example: 30000000
        hash:
          type: string
          description: The hash of the block.
          example: 20e93738606e150ea3f2dd30b4b60fd9af2db05b6aecdd1201159a4e50455d44
        difficulty:
          type: integer
          description: The difficulty of the block.
          example: 74
        reward:
          type: integer
          description: The reward of the block.
          example: 6000000
