name: Build check

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    env:
      BOOST_ROOT: C:/hostedtoolcache/windows/Boost/1.72.0/x86_64
    steps:
      - uses: actions/checkout@master

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Boost
        shell: powershell
        run: |
          echo "${env:BOOST_ROOT}"
          $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
          (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
          Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=${env:BOOST_ROOT}"

      - name: Build
        shell: powershell
        id: build
        run: |
          $build_folder = "build"
          $sha = "${{ github.sha }}"
          $ccx_ver = $sha.SubString(0,7)
          $release_name = "ccx-cli-win64-v$ccx_ver"
          mkdir "$build_folder"
          cd "$build_folder"
          cmake -G "Visual Studio 16 2019" ..
          msbuild concealX.sln /p:Configuration=Release /m
          cd src\Release
          Compress-Archive -Path *.exe -DestinationPath "$release_name.zip"
          $sha256 = (Get-FileHash "$release_name.zip").Hash
          $asset_path = "./$build_folder/src/Release/$release_name.zip"
          mkdir "$release_name"
          cp *.exe "$release_name/"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=ccx_ver::${ccx_ver}"
          echo "::set-output name=artifact_path::$build_folder/src/Release/$release_name"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-18.04
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "CCX_VERSION=$ccx_version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake gcc g++ libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-20.04
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "CCX_VERSION=$ccx_version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake gcc g++ libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu20-clang:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=ubuntu-20.04-clang
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "CCX_VERSION=$ccx_version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake clang libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          CC=clang CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos10:
    name: macOS 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=macos-10.15
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "CCX_VERSION=$ccx_version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          brew install boost

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos11:
    name: macOS 11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=macos-11
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "CCX_VERSION=$ccx_version" >> $GITHUB_ENV
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV
          echo "::set-output name=release_name::${release_name}"

      - name: Install dependencies
        run: |
          brew install boost

      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
